name: imcrypto
description: A multi-chain crypto wallet app
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  web3dart: ^2.7.1
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  http: ^1.1.0
  bip39: ^1.0.6
  hex: ^0.2.0
  ed25519_hd_key: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true