name: imcrypto
description: A multi-chain crypto wallet app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  web3dart: ^2.7.1
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  http: ^1.1.0
  bip39: ^1.0.6
  hex: ^0.2.0
  ed25519_hd_key: ^2.2.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/
    - assets/onboarding/wallet.png

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon2.png"
  android: true
  remove_alpha_android: true
